- name: Enable Ondrej PHP repo
  apt_repository: repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_lsb.codename }} main' state=present

- name: Install PHP 7.2 packages
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - php7.2-bz2
    - php7.2-bcmath
    - php7.2-common
    - php7.2-cli
    - php7.2-curl
    - php7.2-dev
    - php7.2-gd
    - php7.2-fpm
    - php7.2-json
    - php7.2-opcache
    - php7.2-mbstring
    - php7.2-mysql
    - php7.2-xml
    - php-memcached
    - php-xdebug
    - php7.2-intl
    - php7.2-soap
    - php7.2-xsl
    - php7.2-zip
    - libapache2-mod-php7.2

- name: Push out 7.2 php.ini file
  template:
    src: etc/php/7.2/fpm/php.ini
    dest: /etc/php/7.2/fpm/php.ini
  notify: php7.2-fpm restart

- name: Set the max file upload size
  ini_file:
    dest: /etc/php/7.2/fpm/php.ini
    section: "PHP"
    option: "{{ item }}"
    value: "{{ file_upload_max_size }}M"
  with_items:
    - upload_max_filesize
    - post_max_size
  notify: php7.2-fpm restart

- name: Set 7.2 values in php.ini cli
  ini_file:
    dest: /etc/php/7.2/cli/php.ini
    section: "PHP"
    option: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: "short_open_tag", value: "On" }
  notify: php7.2-fpm restart
